sonar.projectKey=umbora-frontend
sonar.projectName=UmBora_Frontend
sonar.host.url=https://sedimentologic-crescentlike-tijuana.ngrok-free.dev
sonar.token=sqa_b7176c456074805866dc6a3e4aac82e2d0319445
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info