sonar.projectKey=umbora-backend
sonar.projectName=UmBora_Backend
sonar.host.url=https://sedimentologic-crescentlike-tijuana.ngrok-free.dev
sonar.token=sqa_b7176c456074805866dc6a3e4aac82e2d0319445
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,tests/**,migrations/**,scripts/**,sonar-project.properties
sonar.javascript.lcov.reportPaths=coverage/lcov.info